services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "5173:5173"
    entrypoint: ["./entrypoint.sh"]
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    entrypoint: ["sh", "-c", "bash ./dev-start-backend.sh"]
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
  celery:
    build:
      context: ./backend
      dockerfile: DockerFile
    entrypoint: ["sh", "-c", "celery -A cel.app.celery_app worker -l info"]
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
  celery-beat:
    build:
      context: ./backend
      dockerfile: DockerFile
    entrypoint: ["sh", "-c", "celery -A cel.app.celery_app beat -l info"]
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7
    ports:
      - "6379:6379"


volumes:
  mongo-data: