FROM python:3.13-slim 

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ./requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Install ngrok
RUN apt-get update && apt-get install -y curl unzip && \
    curl -L https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -o ngrok.zip && \
    unzip ngrok.zip -d /usr/local/bin && \
    rm ngrok.zip && \
    apt-get clean

